[package]
name = "raytracer"
version = "0.1.0"
authors = ["heftyfunseeker <niccosimone@gmail.com>"]

[dependencies]
rusty_math = { git = "https://github.com/heftyfunseeker/rusty-math.git" }
rand = "*"
